{% set version = "5.15.8" %}

package:
  name: qt-gtk-platformtheme
  version: {{ version }}

source:
  # We only need to download the smaller qt-base, not qt-main for this plugin
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/qtbase-everywhere-opensource-src-{{ version }}.tar.xz
  sha256: bfb11126c7f3abc3fdf86425ce912988b864a7e79a606d77325cffdbacb4be9c  # 5.15.8

build:
  number: 1
  skip: true  # [not linux]
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt-gtk-platformtheme', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make                               # [unix]
    - jom                                # [win]
    - ninja
    - perl
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - qt-main {{ version }}             # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
  host:
    - qt-main {{ version }}
    - glib
    - gtk3
    - pango
    - atk
    - cairo
    - gdk-pixbuf
    - xorg-libxinerama
    - xorg-libxrandr
    - xorg-libxcursor
    - xorg-libxcomposite
    - xorg-libxdamage
    - xorg-xineramaproto
  run:
    # We want to be pinned to the exact qt version
    - qt-main {{ version }}

test:
  commands:
    - test -f "${PREFIX}/plugins/platformthemes/libqgtk3${SHLIB_EXT}"

about:
  home: http://qt-project.org
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: Qt GTK3 platform theme
  dev_url: https://github.com/qt/qtbase/tree/5.15/src/plugins/platformthemes/gtk3


extra:
  recipe-maintainers:
    - conda-forge/qt-main
