github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
os_version:
  linux_64: cos7
provider:
  linux_aarch64: default
build_platform:
<<<<<<< HEAD
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
bot:
  abi_migration_branches:
  - 'qt6'
=======
  linux_aarch64: linux_64
>>>>>>> upstream/qt6
